[platformio]
default_envs = esp32-s3

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:esp32-c3]
board = esp32-c3-devkitm-1

[env:esp32-s3]
board = esp32-s3-devkitc-1

[env:esp32-c6]
board = esp32-c6-devkitc-1
